spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengramremind
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.green.greengram-remind
  mapper-locations: mappers/**/*.xml

server:
  port: 8090